import logo from "../../../assets/logo/logo.png";
import loginStocks from "../../../assets/images/login-stocks.png";
const LoginContent = () => {
  return (
    <div className="w-3/5 max-h-full flex flex-col pl-12 justify-end leading-5 mobile:w-2/4 laptop:pl-6 tablet:w-full tablet:px-12">
      <img src={logo} alt="logo" className="max-w-[30%]" />
      <strong className="mt-4">Dear Valued Investors,</strong>
      <p>
        We are delighted to offer you a unique opportunity to earn returns on
        your investments/trades made through the demat account opened under our
        esteemed platform. As part of our commitment to your success, we are
        pleased to announce that we provide a 50% share of the brokerage
        generated by your transactions.
      </p>
      <strong className="mt-6 mb-2">Highlights of our offering:</strong>
      <p>
        <strong className="pr-1">Swift Withdrawals:</strong>
        Withdrawal within 48 hours through your registered payment method.{" "}
        <br />
        <strong className="mt-1 pr-1">User-Friendly Dashboard:</strong>
        Personalized dashboard to track daily brokerage updates.
      </p>
      <img
        src={loginStocks}
        alt="login-stocks-market"
        className="mt-4 max-w-[50%]"
      />
    </div>
  );
};
export default LoginContent;
